### ISSUE TITLE
Migration fixes

### ISSUE THREAD

**Issue by davestewart** [spectre-org/spectre-docs#4]
Fix minor issues with the initial migration:

Sidebar

- [ ] headers have too much padding
  - check the h2 tag
- [x] active links not showing
  - Check VPSidebarItem
- [x] mobile icon trigger not showing correctly
  - framework `menu` class clashes with spectre `menu` class

containers

- [x] too much padding
  - add classes to nuke it / check VitePress styles

Buttons

- [x] no space between them

Forms

- [x] intermediate checkbox unchecked

Menu

- [x] dropdown buttons don't work

Modals

- [x] modal doesn't show
  - check :target property of #example-modal-1

Tiles

- [x] no space between buttons

Off canvas

- [x] doesn't show on resize / click

Media

- [x] video is private

Misc

- [x] various links to `https://github.com/picturepan2/spectre`

**Comment by niutech** [comment]
As for modals not opening, this is probably due to some JS such as: `window.addEventListener("hashchange",l=>{l.preventDefault()})` blocking `.modal:target` CSS.

**Comment by davestewart** [comment]
OK, have tracked down the `:target` issue (which affects modal, dropdown and off-canvas) to be [internal functionality](https://github.com/vuejs/vitepress/blob/main/src/client/app/router.ts#L238-L240) of the VitePress Router:

- https://discord.com/channels/325477692906536972/790509637598314527/1227615250166059161

I'll look to create an issue about this, and either:

- PR a fix
- use something like [JSCodeShift](https://github.com/facebook/jscodeshift) to disable that code

Will post VitePress issue link when I have it.

**Comment by niutech** [comment]
@davestewart The `:target` issue in Vitepress has already been submitted: https://github.com/vuejs/vitepress/issues/2984

**Comment by davestewart** [comment]
Yup - just committed and pushed!

BTW – great detective work / docs reading there.

It's really appreciated 🙏

**Comment by davestewart** [comment]
Rats – it seems that the modal close button / hash-change scrolls to the top of the page if the id doesn't exist:

```html
<a class="btn btn-link" href="#modals">Close</a>
```

**Comment by niutech** [comment]
If you put a non-existent hash in `<a href="#close" class="modal-overlay" aria-label="Close"></a>`, it shouldn't scroll anywhere, at least in Chromium. Otherwise try this: `<a href="#close" id="close" class="modal-overlay" aria-label="Close"></a>`.

**Comment by davestewart** [comment]
@niutech – hey... have finally got back on this.

So modal craziness is 100% to do with VitePress and its router. There's been lots of updates since I started this, and it still appears to be a problem, even with teh `vp-raw` or `::: raw` options. However, I've gotten it to work by adding Vue event handlers directly in the markup, so I'll accept that workaround for the time being.

BTW, it's clear you're interested in pushing Spectre forwards with your fork. Would you be interested in coming on as a another maintainer for this org?
